name: Terraform CI

on:
  push:
    paths:
      - "Deploying a Serverless Application using GCP Cloud Functions and Terraform/**"
  pull_request:
    paths:
      - "Deploying a Serverless Application using GCP Cloud Functions and Terraform/**"
  workflow_dispatch: {}

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform fmt
        working-directory: "Deploying a Serverless Application using GCP Cloud Functions and Terraform"
        run: terraform fmt -check

  validate:
    runs-on: ubuntu-latest
    needs: [fmt]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init & Validate
        working-directory: "Deploying a Serverless Application using GCP Cloud Functions and Terraform"
        run: |
          terraform init -input=false
          terraform validate

  plan:
    runs-on: ubuntu-latest
    needs: [validate]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Plan
        working-directory: "Deploying a Serverless Application using GCP Cloud Functions and Terraform"
        env:
          GOOGLE_CLOUD_KEYFILE_JSON: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          TF_VAR_project: ${{ secrets.GCP_PROJECT }}
        run: |
          terraform init -input=false
          terraform plan -no-color -out=plan.tfplan

  apply:
    runs-on: ubuntu-latest
    needs: [plan]
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Apply
        working-directory: "Deploying a Serverless Application using GCP Cloud Functions and Terraform"
        env:
          GOOGLE_CLOUD_KEYFILE_JSON: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          TF_VAR_project: ${{ secrets.GCP_PROJECT }}
        run: |
          terraform init -input=false
          terraform apply -auto-approve plan.tfplan
